// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Priority } from "./Priority";

/**
 * What the Add dialog collects.
 */
export type AddRequest = { url: string, 
/**
 * Falls back to the configured download directory.
 */
dest_dir: string | null, 
/**
 * Overrides the server-supplied name.
 */
filename: string | null, category: string | null, 
/**
 * `None` lets the governor decide, which is almost always the right answer.
 */
max_conns: number | null, priority: Priority, 
/**
 * False means "add to queue": it is enqueued but not jumped to the front.
 */
start_now: boolean, expected_sha256: string | null, };
