// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkerState } from "./WorkerState";

/**
 * One worker's state, for the Details drawer's connection table.
 */
export type ConnectionSnapshot = { id: number, bytes: number, bps: number, retries: number, 
/**
 * The half-open byte range this worker currently owns, if it holds a claim.
 */
claim_start: number | null, claim_end: number | null, state: WorkerState, };
