// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConnectionSnapshot } from "./ConnectionSnapshot";

/**
 * The connection table for one download.
 */
export type ConnectionsSnapshot = { id: string, connections: Array<ConnectionSnapshot>, };
