// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DownloadStatus } from "./DownloadStatus";
import type { ValidationState } from "./ValidationState";

/**
 * One row in the downloads list.
 */
export type DownloadSummary = { id: string, filename: string, 
/**
 * Redacted. Signed links are bearer credentials and the list is the last place one should
 * be visible.
 */
url_redacted: string, host: string, dest_dir: string, category: string, total_size: number | null, bytes_done: number, status: DownloadStatus, validation_state: ValidationState, 
/**
 * Set only while queued.
 */
queue_position: number | null, created_at: number, completed_at: number | null, error: string | null, 
/**
 * Whether the server supports picking up where this left off.
 */
resumable: boolean, };
