// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConnectionSnapshot } from "./ConnectionSnapshot";
import type { DownloadSummary } from "./DownloadSummary";
import type { EventRow } from "./EventRow";
import type { RangeSupport } from "./RangeSupport";
import type { UrlHistoryRow } from "./UrlHistoryRow";

/**
 * Everything behind the Details drawer.
 */
export type DownloadDetails = { summary: DownloadSummary, original_url_redacted: string, final_url_redacted: string, etag: string | null, last_modified: string | null, content_type: string | null, http_version: string | null, accept_ranges: RangeSupport, max_connections: number | null, retry_count: number, url_refresh_count: number, part_path: string, 
/**
 * How many contiguous spans the completed bytes form. One means a clean prefix; more
 * means segmented progress, which is what the user is paying connections for.
 */
completed_spans: number, 
/**
 * Live, and empty whenever the download is not running.
 */
connections: Array<ConnectionSnapshot>, url_history: Array<UrlHistoryRow>, 
/**
 * What has happened to this download, oldest first.
 */
timeline: Array<EventRow>, };
