// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConnectionsSnapshot } from "./ConnectionsSnapshot";
import type { Notice } from "./Notice";
import type { ProgressSnapshot } from "./ProgressSnapshot";
import type { StateChanged } from "./StateChanged";

/**
 * Everything the engine emits.
 */
export type EngineEvent = { "event": "progress", downloads: Array<ProgressSnapshot>, } | { "event": "state" } & StateChanged | { "event": "connections" } & ConnectionsSnapshot | { "event": "notice" } & Notice;
