// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One entry in a download's timeline.
 *
 * Deliberately coarse. This is a record of decisions -- queued, started, paused, link
 * replaced -- not a log: a per-chunk trace would be both enormous and useless to the person
 * reading it, who wants to know what happened to their download and when.
 */
export type EventRow = { seq: number, at: number, kind: string, 
/**
 * Free text, already redacted where it mentions a URL.
 */
detail: string, };
