// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ManagerError = { "kind": "not_found", "message": string } | { "kind": "store", "message": string } | { "kind": "probe", "message": string } | { "kind": "refresh", "message": string } | { "kind": "io", "message": string } | { "kind": "invalid", "message": string };
