// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Something that needs the user, phrased in terms the user can act on.
 *
 * Deliberately not an error type. `ErrorClass` says what went wrong technically; a `Notice`
 * says what the user is being asked to decide. The two do not map one-to-one — most errors
 * are retried silently and never surface here at all.
 */
export type Notice = { "kind": "url_expired", id: string, filename: string, bytes_done: number, total: number | null, } | { "kind": "disk_full", id: string, filename: string, needed_bytes: number, } | { "kind": "failed", id: string, filename: string, message: string, } | { "kind": "completed", id: string, filename: string, path: string, 
/**
 * Present when `hash_on_complete` was set.
 */
sha256: string | null, };
