// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Queue ordering. `Ord` runs Low < Normal < High, so higher priority sorts later and the
 * queue is read in descending order.
 */
export type Priority = "low" | "normal" | "high";
