// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DownloadSummary } from "./DownloadSummary";

/**
 * What the Add dialog shows before committing to anything.
 */
export type ProbePreview = { url_redacted: string, final_url_redacted: string, filename: string, total_size: number | null, resumable: boolean, segmentable: boolean, content_type: string | null, http_version: string, redirects: number, 
/**
 * Incomplete downloads that look like this one (§D.10.7). Weak evidence by construction —
 * enough to offer a resume, never enough to assume one.
 */
existing: Array<DownloadSummary>, };
