// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DownloadStatus } from "./DownloadStatus";

/**
 * One download's state at a moment in time.
 *
 * Cheap to produce and safe to drop: every field is absolute rather than a delta, so a UI
 * that misses a tick shows slightly stale numbers instead of drifting permanently.
 */
export type ProgressSnapshot = { id: string, status: DownloadStatus, bytes_done: number, 
/**
 * `None` when the server never told us the size. The UI must render an indeterminate bar
 * rather than inventing a denominator.
 */
total: number | null, current_bps: number, avg_bps: number, peak_bps: number, 
/**
 * Whole seconds remaining. `None` when there is no size, or when the current rate is zero
 * and any estimate would be a fabrication.
 */
eta_secs: number | null, conns: number, retries: number, };
