// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What we learned about the server's range support. `Unknown` never occurs after a
 * successful probe; it exists for records loaded from an older schema.
 */
export type RangeSupport = "unknown" | "supported" | "unsupported" | "lied";
