// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The three result cards of the refresh dialog, plus the non-resumable case.
 */
export type RefreshOutcome = "verified" | "confirm" | "reject" | "restart_only";
