// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RefreshOutcome } from "./RefreshOutcome";

/**
 * The read-only half of a URL swap. Produced without mutating anything.
 */
export type RefreshReport = { outcome: RefreshOutcome, 
/**
 * Plain language, for the card. Never mentions ETags, 206s or byte offsets.
 */
message: string, windows_checked: number, 
/**
 * What proving identity cost. The feature exists to avoid re-transferring data, so this
 * number is reported rather than buried.
 */
bytes_verified: number, 
/**
 * What resuming would keep.
 */
preserved_bytes: number, total_size: number | null, resumable: boolean, };
