// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DownloadStatus } from "./DownloadStatus";

/**
 * A status transition worth re-rendering for.
 *
 * Low frequency by construction: a download changes status a handful of times in its life,
 * so the UI can afford to refetch the full record when one arrives.
 */
export type StateChanged = { id: string, status: DownloadStatus, 
/**
 * Present when the transition was a failure.
 */
error: string | null, };
