// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CollisionPolicy } from "./CollisionPolicy";

/**
 * Settings as the Settings view wants them.
 *
 * [`Settings`] is the engine's own type and carries `Duration`s, which serde renders as
 * `{ "secs": 15, "nanos": 0 }` — correct, and useless to bind a number input to. This is the
 * same settings expressed for a form, and it is the only shape the UI ever sees.
 */
export type UiSettings = { download_dir: string, max_concurrent_downloads: number, max_conns_per_download: number, max_total_conns: number, max_conns_per_host: number, adaptive_concurrency: boolean, max_retries_per_segment: number, connect_timeout_secs: bigint, read_idle_timeout_secs: bigint, stall_timeout_secs: bigint, max_redirects: number, block_insecure_redirect: boolean, paranoid_recovery: boolean, hash_on_complete: boolean, apply_motw: boolean, collision_policy: CollisionPolicy, user_agent: string, };
