// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One row of the redacted link history, for the Links tab.
 */
export type UrlHistoryRow = { seq: number, url_redacted: string, host: string, source: string, outcome: string, bytes_done_at_swap: number, added_at: number, };
