// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ValidationState = "not_required" | "auto_verified" | "content_verified" | "user_confirmed" | "rejected";
